ITEM.name = "Blue Chair"
ITEM.description = "Blue Chair"
ITEM.category = "Constructable"
ITEM.model = "models/Items/item_item_crate.mdl"
ITEM.prop = "models/props_c17/chair02a.mdl"
ITEM.offset = Vector(0,0,12)
ITEM.maxdistance = 200
ITEM.mindistance = 80
ITEM.defaultturn = 180
ITEM.time = 2
ITEM.width = 1
ITEM.height = 1
