ITEM.name = "Wood Cabinet"
ITEM.description = "A Cabinet"
ITEM.category = "Constructable"
ITEM.model = "models/Items/item_item_crate.mdl"
ITEM.prop = "models/props_interiors/Furniture_shelf01a.mdl"
ITEM.offset = Vector(0,0,32)
ITEM.maxdistance = 200
ITEM.mindistance = 80
ITEM.defaultturn = 180
ITEM.time = 15
ITEM.width = 2
ITEM.height = 3
