ITEM.name = "Metal Sheet"
ITEM.description = "A Metal Sheet."
ITEM.category = "Constructable"
ITEM.model = "models/Items/item_item_crate.mdl"
ITEM.prop = "models/props_debris/metal_panel02a.mdl"
ITEM.offset = Vector(0,0,32)
ITEM.maxdistance = 200
ITEM.mindistance = 40
ITEM.defaultturn = 0
ITEM.time = 10
ITEM.width = 1
ITEM.height = 2
