ITEM.name = "Potted Plant"
ITEM.description = "A potted Plant"
ITEM.category = "Constructable"
ITEM.model = "models/Items/item_item_crate.mdl"
ITEM.prop = "models/props_lab/cactus.mdl"
ITEM.offset = Vector(0,0,5)
ITEM.maxdistance = 200
ITEM.mindistance = 80
ITEM.defaultturn = 90
ITEM.time = 2
ITEM.width = 1
ITEM.height = 1
