ITEM.name = "Rounded Table"
ITEM.description = "Round Table"
ITEM.category = "Constructable"
ITEM.model = "models/Items/item_item_crate.mdl"
ITEM.prop = "models/props_c17/FurnitureTable001a.mdl"
ITEM.offset = Vector(0,0,16)
ITEM.maxdistance = 200
ITEM.mindistance = 80
ITEM.defaultturn = 180
ITEM.time = 10
ITEM.width = 2
ITEM.height = 2
